name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install libhidapi-dev
    - name: Build
      run: make

  osx-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        brew update
        brew install hidapi
    - name: Build
      run: make
